# tmuxinator configuration file for working on the thesis

name: thesis
root: .

windows:
  - thesis:
      layout: even-horizontal
      panes:
        -
        -
  - code:
      layout: even-horizontal
      panes:
        -
        -
  - evaluation:
      layout: even-horizontal
      panes:
        -
        -
