#
# @TODO This is not a working `yaml` file. It is just ideas for how the hpa for
# the test server will work. Since the prediction option is set using
# `annotate`, this `yaml` file can be used for both predictive and reactive
# autoscaling.
#
# The following file is used as a guide:
# http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/hpa-php-apache.yaml
#

apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: test-server
  namespace: default
spec:
  scaleRef:
    kind: ReplicationController
    name: test-server
    subresource: scale
  # These values are very much made up.
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization:
    targetPercentage: 70
