apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: test-server
  namespace: default
spec:
  scaleRef:
    kind: ReplicationController
    name: test-server
    subresource: scale
  minReplicas: 1
  maxReplicas: 30
  cpuUtilization:
    targetPercentage: 80
